Eu estava com a versão anterior, bah.
ReiLoko4/manga-you-know pull request #1
Opened 2023-08-28 03:21 UTC by KingTimer12

Minha versão, antes da tua última atualização, tinha o problema envolvendo a altura. Passei esse meio tempo resolvendo isso e se quiser retirar o método, tudo bem. Além de colocar um `ft.Container` nos cards para conseguir manipular o `margin` e deixar, na minha concepção, mais bonitinho. Ademais, tirei o `database` que fica dentro da pasta do programa, sendo mais específico: tirei os arquivos de dentro. Coloquei também uma dependência necessária no `requirements.txt` para caso mais alguém queira ajudar.

Um adendo: coloquei o `ft.Container` na linha 187 para que seja possível usar o `bgColor` para visualizar o `stack.height` melhor.

2023-08-28 18:21 UTC, KingTimer12 commented
Acabei de descobrir que não dá para criar um PR diferente enquanto estiver um aberto 💀 💀 

Enfim, essa última atualização é na parte da velocidade na pesquisa de mangás nos outros sites, no caso só do MangáLivre. Eu fiz os testes e comparei com a versão no vídeo do twitter que você pesquisa por K-On. Eu achei bem mais rápido na forma assíncrona, a que estou usando, do que com multithread. Bem, veja aí os códigos e dê seu veredito final!

(Agora que sei que não dá para criar PR novo enquanto essa estiver aberta, eu vou esperar você olhar antes de fazer qualquer modificação nova)

2023-08-28 18:29 UTC, ReiLoko4 commented
Opa, amigo. Vou dar uma olhada nas suas modificações com mais calma a noite se eu tiver tempo. Agora estou trabalhando então não tenho tanto tempo disponível. Sobre o método pra corrigir a altura dos mangás, o erro só acontece quando se tem um mangá, e antes da versão atual que eu corrigi.
vou dar uma boa olhada sobre o asyncio porque eu já soube sobre melhoras com ele, porém nunca tive paciencia pra aprender a usa lo por suas peculiaridades, mas pode ser no final que não mude nada devido ao fato que a API do MangaLivre é meio volatil. Enfim obrigado pela contribuição. Pretendo dar merge sim.

2023-08-28 19:40 UTC, ReiLoko4 commented
Cara eu reli meu comment e eu pareci meio grosso e arrogantekkkkkkkkkkkk.

Mas cara eu realmente sou grato, apenas por você ter gastado seu tempo olhando o meu código, ja fico muito grato.

2023-08-28 21:17 UTC, KingTimer12 commented
Tranquilo, nem senti que foi arrogante ou grossokkkk

Pode ficar tranquilo

2023-08-30 15:05 UTC, ReiLoko4 requested changes
Revert changes on mangalivre.py and fix the things that I ask in the comments.

2023-08-30 15:05 UTC, ReiLoko4 commented on MangaYouKnow/screen/index.py
> +import tracemalloc
remove tracemalloc and trio

2023-08-30 15:05 UTC, ReiLoko4 commented on MangaYouKnow/backend/downloader/mangalivre.py
Runs slower than before

2023-08-30 15:05 UTC, ReiLoko4 commented on MangaYouKnow/screen/favorites.py
> +import trio
remove trio

2023-08-30 15:05 UTC, ReiLoko4 commented on MangaYouKnow/screen/reader.py
> +import trio
remove trio

2023-08-30 15:05 UTC, ReiLoko4 commented on requirements.txt
> +httpx
remove httpx, asyncio and pyclip (the last is my error)

2023-08-30 22:14 UTC, ReiLoko4 approved these changes
Approved.

2023-08-30 22:14 UTC, merged